### ISSUE TITLE
App is not install.

### ISSUE THREAD

**Issue by sunnynegi** [hiteshsahu/React-Native-Music-Player#1]
HI there.
After cloning your project app is not install on android phone, or this project is not maintain by developers

Steps:-
1. Clone the project.
2. Npm install.
3. react-native run-android  it's throw error
`Scanning 627 folders for symlinks in /home/sunny/projects/React-Native-Music-Player/node_modules (4ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
`

**Comment by hiteshsahu** [comment]
Issue is self explanatory, there is issue with your testenvironment. You need have a device or emulator to running so that react can install app.
